In [1]:
import numpy as np

In [2]:
def array_factory(mode, shape, value=None):
    '''
    Creates various NumPy arrays based on the selected mode.

    Args:
        mode (int): Array type:
            0 for zeros,
            1 for ones,
            2 for full,
            3 for identity.
        shape (int or tuple): Shape/size of the array.
        value (optional): Value used when mode is 2.

    Returns:
        np.ndarray: The generated NumPy array.

    Example:
        array_factory(0, (2, 3))
        array([[0., 0., 0.],
               [0., 0., 0.]])
    '''
    try:
        if mode == 0:
            return np.zeros(shape)

        elif mode == 1:
            return np.ones(shape)

        elif mode == 2:
            if value is None:
                raise ValueError("Value is required for mode 2.")
            return np.full(shape, value)

        elif mode == 3:
            return np.identity(shape)

        else:
            raise ValueError("Invalid mode. Choose 0, 1, 2, or 3.")

    except (ValueError, TypeError) as e:
        print(f"Error: {e}")
        return None

In [3]:
print(array_factory(0,(2,2)))
print('================================')
print(array_factory(1,(3,7)))
print('================================')
print(array_factory(2,(2,3),0.3))
print('================================')
print(array_factory(3,4))
print('================================')

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[0.3 0.3 0.3]
 [0.3 0.3 0.3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
def secure_reshape_and_stack(data1, data2, new_shape):
    '''
    Validates and converts inputs to NumPy arrays,
    reshapes the first dataset, and vertically stacks
    both datasets.

    Args:
        data1 (array-like): First dataset.
        data2 (array-like): Second dataset.
        new_shape (tuple): New shape for the first dataset.

    Returns:
        np.ndarray: The vertically stacked array.

    Example:
        secure_reshape_and_stack([1, 2, 3, 4], [[5, 6], [7, 8]], (2, 2))
        array([[1, 2],
               [3, 4],
               [5, 6],
               [7, 8]])
    '''
    try:
        # Convert inputs to NumPy arrays
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Reshape the first dataset
        arr1 = arr1.reshape(new_shape)

        # Vertically stack both arrays
        result = np.vstack((arr1, arr2))

        return result

    except (ValueError, TypeError) as e:
        print(f"Error: {e}")
        return None

In [5]:
data1 = [1, 2, 3, 4]
data2 = [[5, 6], [7, 8]]

result = secure_reshape_and_stack(data1, data2, (2, 2))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
class Solution:

    def romanToInt(self, s: str) -> int:
        '''
        Convert a Roman numeral to an integer.

        Args:
            s (str): A valid Roman numeral.

        Returns:
            int: The integer representation of the Roman numeral.

        Example:
            Solution().romanToInt("CIV")
            104
        '''
        values: dict[str, int] = {
            "I": 1,
            "V": 5,
            "X": 10,
            "L": 50,
            "C": 100,
            "D": 500,
            "M": 1000
        }

        total = 0

        for i in range(len(s)):
            if i + 1 < len(s) and values[s[i]] < values[s[i + 1]]:
                total -= values[s[i]]
            else:
                total += values[s[i]]

        return total

In [14]:
solution = Solution()

print(solution.romanToInt("III"))      # Expected: 3
print(solution.romanToInt("LVIII"))    # Expected: 58
print(solution.romanToInt('CIV'))
print(solution.romanToInt("MCMXCIV"))  # Expected: 1994

3
58
104
1994


In [15]:
class Solution:
    def searchInsert(self, nums: list[int], target: int) -> int:
        '''
        Return the index where target is found or should be inserted.

        Args:
            nums (list[int]): A sorted list of distinct integers.
            target (int): The value to search for.

        Returns:
            int: The index of target or its correct insertion position.

        Example:
            searchInsert([1, 3, 5], 2)
            1
        '''
        left = 0  #0 -> 1
        right = len(nums) - 1 #2 -> 1 -> 0

        while left <= right:
            mid = (left + right) // 2

            if nums[mid] == target:
                return mid

            elif nums[mid] < target:
                left = mid +1

            else:
                right = mid - 1

        return left

# Example usage:
s=Solution()
nums = [1, 3, 5, 7, 9, 11]
print(s.searchInsert(nums, 7))   # Output: 3
print(s.searchInsert(nums, 15))   # Output: 6


3
6


In [10]:
class Solution:

    def calculate(self, s: str) -> int:
        '''
        Evaluate a mathematical expression containing +, -, *, and /.

        Args:
            s (str): A valid expression containing non-negative integers
                and the operators +, -, *, /.

        Returns:
            int: The evaluated result. Division truncates toward zero.

        Example:
            calculate("3+2*2")
            7

            calculate("3/2")
            1
        '''

        stack = []
        num = 0
        operator = "+"

        for i, char in enumerate(s):

            if char.isdigit():
                num = num * 10 + int(char)
            # Process the number when the current character is an operator
            # or when we reach the end of the string.
            if (not char.isdigit() and char != " ") or i == len(s) - 1:

                if operator == "+":
                    stack.append(num)

                elif operator == "-":
                    stack.append(-num)

                elif operator == "*":
                    stack.append(stack.pop() * num)

                elif operator == "/":
                    previous = stack.pop()
                    stack.append(int(previous / num))

                operator = char
                num = 0

        return sum(stack)


test = Solution()

s = '5*7/2'

print(test.calculate(s))

17
